### ISSUE TITLE
ccxt exchange no longer supported

### ISSUE THREAD

**Issue by JulesText** [eprbell/dali-rp2#107]
Hi there,

The exchange 'liquid' is required by dali when ccxt is imported upon commands. However this exchange is no longer supported in ccxt 2.4.x. 

When running the dali command:
dali_us -s -o output -p test_ input/test_config.ini

The following error is generated:
ImportError: cannot import name 'liquid' from 'ccxt' (/usr/local/lib/python3.9/site-packages/ccxt/__init__.py)

Potentially the fix is to remove references to 'liquid' from the dali file plugin/pair_converter/ccxt.py

The exchange was supported in ccxt v2.2.1 so in lieu of a PR, if dali users encounter the same error, they can install this previous version of ccxt and dali should run okay.

Cheers!

**Comment by eprbell** [comment]
Thanks for reporting the bug! @macanudo527 , I suggest fixing the version of CCXT in setup.cfg, so that when CCXT makes such changes it won't affect us (and you'll be able to update the version in setup.cfg whenever you like).

**Comment by JulesText** [comment]
The only exception I see is if the exchange api configuration defined in ccxt becomes outdated and needs a new ccxt configuration to connect to the exchange, though from my limited experience exchanges seem to retain their legacy apis so this would seem to be a pretty rare situation. Also from what little I know of dali, it will try several exchanges in succession to query historical price data, so there's a safe logical process if one exchange fails to query then another one can be tried.

**Comment by macanudo527** [comment]
@JulesText are you sure you are working with them latest version of Dali? This was fixed in a PR about 3 weeks ago. It should have been replaced with Houbi to resolve prices for SOLO. 

Ftx was removed as well.

**Comment by JulesText** [comment]
Hi @macanudo527 thanks for asking. I can see the ccxt.py at [this link](https://github.com/eprbell/dali-rp2/blob/main/src/dali/plugin/pair_converter/ccxt.py) has been updated with the PR #98 

I have installed v0.6.1 (which I thought was the latest version) via PyPI and you can see the ccxt.py file in the package at [this link]([url](https://pypi.org/project/dali-rp2/#files)) contains the reference to liquid.

Its probably just a matter of waiting until the PR flows through the staging process and is pushed to PyPI. The PR you did looks good to me :)

**Comment by eprbell** [comment]
Ah, yes, I do need to make a new release, since it's been a while since the last one: I'll probably get to it this weekend.

**Comment by macanudo527** [comment]
Has this been resolved?

**Comment by eprbell** [comment]
My bad, I haven't made a new release. Working on it now.

**Comment by eprbell** [comment]
Just uploaded new release of RP2 and DaLI to Pypi:
* https://pypi.org/project/rp2/
* https://pypi.org/project/dali-rp2/

Note that I had to [disable a test](https://github.com/eprbell/dali-rp2/commit/bc817f8fcce5dbe194055181f4b52d6867f14dbf) that was getting stuck (you may want to take a look at it when you have some time):

**Comment by macanudo527** [comment]
I think that is because Binance is unavailable for you now. I'll have to rewrite it when I revise the CCXT pair converter.
