### ISSUE TITLE
CCXT Pair Converter may not be available for people in the US

### ISSUE THREAD

**Issue by macanudo527** [eprbell/dali-rp2#110]
It seems like the Binance Public API has been geolocked for the US. Since Binance is the default exchange for the CCXT pair converter, pricing might not be available for those using Dali-RP2 in the US.

We need another default exchange. Kraken is good candidate, but fetching pricing is really slow.

**Comment by eprbell** [comment]
What a pain in the neck... Kraken seems like a good alternative and hopefully caching will help with slowness issues.

**Comment by macanudo527** [comment]
It's just a simple line change. But, any prices from the last full quarter on (currently Q42022~) will take 5 seconds to retrieve. 

The KuCoin API seems more responsive and has more markets, but prices start 9/2017. Kraken has a deeper history.

Can you access [Binance's CSV files](https://data.binance.vision/?prefix=data/spot/daily/klines/)? Can you click the link and see if you are locked out? That is another option as well. 

Obviously, it would beneficial for users to set this as a parameter as well.

**Comment by eprbell** [comment]
Should we implement #61 to fix this? That would give users full flexibility to choose what they want, I think. I can access the Binance CSV files you linked.

**Comment by macanudo527** [comment]
This has been resolved with #115 .
