### ISSUE TITLE
Kraken CSV reader creates too large of cache for multiple assets

### ISSUE THREAD

**Issue by macanudo527** [eprbell/dali-rp2#120]
If a user has more than about 3 assets, pickling the data files uses a lot of memory 30gb+ and may cause the program to terminate.

I think I'll have to work out some kind of cache for just the kraken CSV.

Another option is to break the CSV files down into chunks of time and load only the chunk we need. These files would be saved locally. I don't think this poses a security risk. Does anyone know if it does or see an issue with saving the files locally?

**Comment by eprbell** [comment]
I like the idea of preprocessing the CSV files and storing them in manageable chunks. They could be stored in `.dali_cache/kraken/`. How often are these CSV updated (do they reflect the latest prices)? We'll have to decide how to incrementally extract new information getting into the CSV file.

**Comment by macanudo527** [comment]
They just update these once a quarter, and, in theory, they wouldn't revise historical prices, so we would just need to update the most recent quarter. They have incremental updates but they are in a separate new folder, so that would need to be added to the code every time they are released. I guess I could build an intelligent search function, but it would rely on them keeping the same naming convention I think. Anyway, we can just try to download the file again if the price is not available.

**Comment by eprbell** [comment]
If at all possible, I'd avoid relying on their naming convention. Also having to change the code every time a new file is released is not ideal. Perhaps your idea of downloading again if the price is not available would be best.

Question: if they add new price once a quarter, let's say they added the latest prices on Jan 1 and you run DaLI on Feb 1, then there is 1 month of missing prices. In this case the plugin falls back to the REST API for that 1 month, is this correct?

**Comment by macanudo527** [comment]
Sorry, I just realized I never answered your question.

Yes, in this current version of the plugin if no bar is found it returns `None` and the REST API is used.
