### ISSUE TITLE
Does dali-rp2 have a .ods plugin for previous outputs?

### ISSUE THREAD

**Issue by jamesbaber1** [eprbell/dali-rp2#125]
Hi, thanks for all the work on this project. This is awesome.

Maybe I missed this in the docs, but my question is this, is there a way to load in data from your existing .ods output as an input?

Here is my example. I used dali to collect all my trades and price data for 2021. Due to some various complications I had to manually resolve some transactions in the .ods output file before then feeding that into rp2. So I saved the corrected 2021 .ods file.

Now I collected my new inputs using dali, using some of the awesome rest and csv plugins for 2022.  But I would also like to feed in my original 2021 .ods file and combine with the new inputs. 

Is there a way to do this already? Or is there an easy way to combine two .ods files?

Thanks!

**Comment by eprbell** [comment]
Thanks! Take a look at the [manual plugin](https://github.com/eprbell/dali-rp2/blob/main/docs/configuration_file.md#manual-section-csv). It can be used for multiple things:
* resolve partial transactions (without needing to modify the output .ods), or
* read back DaLI output (after some small modifications)

I recommend the first approach, because it doesn't require modifying the DaLI .ods output.

Hope this helps!

**Comment by eprbell** [comment]
No modifications to DaLI source. What I mean is that you can take DaLI output, split it into 3 .csv files (in, out, intra), move the unique_id column to position 0 and feed the result to the manual plugin.

**Comment by jamesbaber1** [comment]
Ahh ok gotcha. Its seems relatively straight forward to write a input plugin after looking at 
https://github.com/eprbell/dali-rp2/blob/424a7e92071244df5434b526e6c074dda548c432/src/dali/plugin/input/csv/manual.py#L37

Would there by any cocerns will me opening a PR with an input ods plugin. (that supports only the rp2 input .ods format)?

I have been meaning to contribute to this at some point, and it seems like an easy way to get more familiar with it

**Comment by eprbell** [comment]
That's an interesting idea: it may be an alternative to the manual plugin, for people who prefer it. Sounds good to me. You may want to look at the [RP2 ods parser](https://github.com/eprbell/rp2/blob/main/src/rp2/ods_parser.py): the code will be very similar (maybe after you're done, we can think about how to factor it).

**Comment by jamesbaber1** [comment]
Ok cool, yea I am actually importing most of all the logic from rp2 and the ods parser. Its looking like it wont be much code at all.

This will help me, because it let me condense down my data to a single ods per year that ill save, and then I can just plug that in and continue on later each year.

**Comment by eprbell** [comment]
This has been implemented in #126
