### ISSUE TITLE
Bitbank Dali Configuration File Documentation

### ISSUE THREAD

**Issue by topherbuckley** [eprbell/dali-rp2#128]
Is the plugin name for the bitbank API really supposed to be `[dali.plugin.input.rest.binance_com <qualifiers>]` as stated in the [Bitbank Section (REST)](https://github.com/eprbell/dali-rp2/blob/main/docs/configuration_file.md#bitbank-section-rest) section of the docs as opposed to `[dali.plugin.input.rest.bitbank <qualifiers>]`? The same applies for the [Bitbank Supplemental Section (CSV)](https://github.com/eprbell/dali-rp2/blob/main/docs/configuration_file.md#bitbank-supplemental-section-csv) I guess this is just a typo, but wanted to confirm before subbmitting a PR in case the [bitbank.py](https://github.com/eprbell/dali-rp2/blob/main/src/dali/plugin/input/rest/bitbank.py) was not ready for use or something.

**Comment by eprbell** [comment]
Those look like typos: thanks for reporting! Go ahead with the PR and we'll merge the fix. @macanudo527

**Comment by macanudo527** [comment]
Yeah, those copy/paste errors. I'll try to patch them up soon. Sorry for the inconvenience.

**Comment by macanudo527** [comment]
This has been resolved with the recent PR. Let us know if you have any other issues.
