### ISSUE TITLE
Implement Ledger CSV Data Loader Plugin

### ISSUE THREAD

**Issue by eprbell** [eprbell/dali-rp2#13]
Writing a [DaLI](https://github.com/eprbell/dali-rp2) data loader plugin has high impact on the functionality and usefulness of both DaLI and [RP2](https://github.com/eprbell/rp2). Data loader plugins are well-defined, encapsulated modules that translate native exchange CSV-based data into DaLI's standard format. As such they are good first issues for newcomers to the the project.

Before starting, please read the [contributing guidelines](https://github.com/eprbell/dali-rp2/blob/main/CONTRIBUTING.md#contributing-to-the-repository).

Plugin development is described in the [developer documentation](https://github.com/eprbell/dali-rp2/blob/main/README.dev.md), in particular read the [Dali Internals](https://github.com/eprbell/dali-rp2/blob/main/README.dev.md#dali-internals) and [Plugin Development](https://github.com/eprbell/dali-rp2/blob/main/README.dev.md#plugin-development) sections, which contain all the information needed to build a new data loader plugin.

The [Trezor plugin](https://github.com/eprbell/dali-rp2/blob/main/src/dali/plugin/input/csv/trezor.py) can be used as an example.

Before submitting a PR for the new plugin, make sure to go through the [DaLI Plugin Laundry List](https://github.com/eprbell/dali-rp2/blob/main/README.dev.md#plugin-laundry-list).

**Comment by stevendavis** [comment]
I can work on this if anyone is still interested.  This project has been quiet for some time.  Everybody doing okay?

**Comment by eprbell** [comment]
Hey there, the project is alive and kicking and it's good to hear back from you! @macanudo527 is working on support for expats using foreign exchanges, which is a large improvement affecting various parts of the code: new binance.com plugin, new CCXT-based abstract class for REST-based plugins, new CCXT-based pair converter plugin (which also contains logic to find a conversion route between non-existing pairs), new Japanese country plugin, etc. (see #45, #53, #44). 

The ledger CSV plugin is all yours :-)

**Comment by eprbell** [comment]
Merged (see #54).
