### ISSUE TITLE
Separate Folder for Sensitive Information

### ISSUE THREAD

**Issue by macanudo527** [eprbell/dali-rp2#135]
Right now, the `input` and `output` folders contain testing data that could be modified and included in a commit.

Would it be better to create a separate standard folder that contains sensitive information like csv files with transaction data or reports generated using personal information? That folder could then be excluded in the `.gitignore` file and there wouldn't be any accidental inclusion of personal information in a commit.

Just a thought.

**Comment by eprbell** [comment]
I recommend keeping your tax inputs in a separate folder (out of the RP2 or DaLI directories): that way it's impossible to check it in by mistake. This is what I do for my own taxes.

**Comment by macanudo527** [comment]
OK, I guess I'm not used to dealing with sensitive info. Maybe I should add some documentation on this to help newbs like me?

**Comment by macanudo527** [comment]
I'm closing this for now. If I have time, I'll try to add docs as a separate issue/PR.
