### ISSUE TITLE
Coinbase REST API: Conversions - Converted From Appear as Negative Value "Buy" in .ods Output file

### ISSUE THREAD

**Issue by jameskupke** [eprbell/dali-rp2#15]
Version: 0.3.21
OS: Fedora Linux 35

On Reviewing transactions outputted from DaLI from the coinbase API, conversions do not appear to be entered correctly.

For example I have a conversion of $2.97 worth of ALGO to BTC, there is a IN entry of BUY -$2.97 in the ALGO tab.

**Comment by eprbell** [comment]
First of all, just wanted to make sure: this is Coinbase, not Coinbase Pro, correct? The Coinbase plugin doesn't support conversions yet (because I don't have an example of them in my transactions). 

Would you be willing to share the one line from your debug logs that shows the JSON returned by Coinbase for this transaction? Before I explain how to do that, let me point out that if you're not comfortable sharing this information, you have a couple of additional options to consider:
* remove personal information from the line: in particular timestamps and ids. If you want to remove/mangle amounts you can do itm but that will probably make it harder to come up with a correct implementation (if you do that, be sure to preserve sign information);
* if you don't want to share the line publicly you also have the option of sharing it privately with me (my Twitter DMs are open: @eprbell).

With that out of the way here's how to do it:
* prepend your dali command line with `LOG_LEVEL=DEBUG `
* after running dali in debug mode, cd to the log directory, open the latest log and grep for the line of the culprit transaction (check in the Coinbase section of the log)

**Comment by jameskupke** [comment]
This is Coinbase, not Coinbase Pro.

I believe here's a transaction:
I masked the date a bit and masked the ids; there appears to be 3 different ids, so I marked with X,Y,Z.


```
2022-03-26 08:27:35,006/dali/DEBUG: Self-contained transaction: InTransaction:
  plugin=Coinbase
  unique_id=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
  raw_data={"id": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX", "type": "trade", "status": "completed", "amount": {"amount": "0.465322", "currency": "XTZ"}, "native_amount": {"amount": "2.91", "currency": "USD"}, "description": null, "created_at": "202X-XX-XXT00:54:55Z", "updated_at": "202X-XX-XXT00:54:57Z", "resource": "transaction", "resource_path": "/v2/accounts/YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY/transactions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX", "instant_exchange": false, "trade": {"id": "ZZZZZZZZ-ZZZZ-ZZZZ-ZZZZ-ZZZZZZZZZZZZ", "resource": "trade", "resource_path": "/v2/accounts/YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY/trades/ZZZZZZZZ-ZZZZ-ZZZZ-ZZZZ-ZZZZZZZZZZZZ"}, "details": {"title": "Converted to Tezos", "subtitle": "Using ALGO Wallet", "header": "Converted 0.465322 XTZ ($2.91)", "health": "positive", "payment_method_name": "ALGO Wallet"}, "hide_native_amount": false}
  timestamp=202X-XX-XX 00:54:55 +0000
  asset=XTZ
  exchange=Coinbase
  holder=<<Name>>
  transaction_type=Buy
  spot_price=6.253733973463537077550599369899
  crypto_in=0.465322
  fiat_fee=0
  fiat_in_no_fee=2.91
  fiat_in_with_fee=2.91
  notes=None
```

**Comment by eprbell** [comment]
Thanks for the data. I think this raw_data is not enough for a conversion because there is only the buy side (0.465322 XTZ) and the fiat amount ($2.91). The following is missing:
- Algorand amount
- fees paid (if any)

Could you check in the file if there is another line (probably in the Algorand section) that describes the sell side? Perhaps look for other occurrences of id (XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX) or maybe trade/id (ZZZZZZZZ-ZZZZ-ZZZZ-ZZZZ-ZZZZZZZZZZZZ).

**Comment by eprbell** [comment]
@houqp submitted a PR to fix this: currently in review.

**Comment by eprbell** [comment]
@jameskupke, any chance you can find the other half of the transaction (the Algorand sell side) in your logs? It would be great to have more data to verify @houqp's fix for this (PR #18). Thanks!

**Comment by jameskupke** [comment]
Ok, let me download 0.3.25 and re-run.

**Comment by jameskupke** [comment]
Ok, I think I found the ALGO to XTC conversion.

Any unique identifiers I tried to match up as best as I could:
```
2022-03-27 18:48:53,969/dali/DEBUG: Self-contained transaction: OutTransaction:
  plugin=Coinbase
  unique_id=AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA
  raw_data={"id": "AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA", "type": "trade", "status": "completed", "amount": {"amount": "-1.549246", "currency": "ALGO"}, "native_amount": {"amount": "-2.97", "currency": "USD"}, "description": null, "created_at": "202X-XX-XXT00:54:56Z", "updated_at": "202X-XX-XXT00:54:56Z", "resource": "transaction", "resource_path": "/v2/accounts/BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBBBB/transactions/AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA", "instant_exchange": false, "trade": {"id": "CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCCCC", "resource": "trade", "resource_path": "/v2/accounts/DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD/trades/CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCCCC"}, "details": {"title": "Converted from Algorand", "subtitle": "Using ALGO Wallet", "header": "Converted 1.549246 ALGO ($2.97)", "health": "positive", "payment_method_name": "ALGO Wallet"}, "hide_native_amount": false}
  timestamp=202X-XX-XX 00:54:56 +0000
  asset=ALGO
  exchange=Coinbase
  holder=<<name>>
  transaction_type=Sell
  spot_price=1.917061589960535641208691196
  crypto_out_no_fee=1.549246
  crypto_fee=0E+27
  crypto_out_with_fee=1.549246
  fiat_out_no_fee=2.97
  fiat_fee=0
  notes=None


2022-03-27 18:48:53,954/dali/DEBUG: Self-contained transaction: InTransaction:
  plugin=Coinbase
  unique_id=EEEEEEEE-EEEE-EEEE-EEEE-EEEEEEEEEEEE
  raw_data={"id": "EEEEEEEE-EEEE-EEEE-EEEE-EEEEEEEEEEEE", "type": "trade", "status": "completed", "amount": {"amount": "0.465322", "currency": "XTZ"}, "native_amount": {"amount": "2.91", "currency": "USD"}, "description": null, "created_at": "202X-XX-XXT00:54:55Z", "updated_at": "202X-XX-XXT00:54:57Z", "resource": "transaction", "resource_path": "/v2/accounts/DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD/transactions/EEEEEEEE-EEEE-EEEE-EEEE-EEEEEEEEEEEE", "instant_exchange": false, "trade": {"id": "CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCCCC", "resource": "trade", "resource_path": "/v2/accounts/DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD/trades/CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCCCC"}, "details": {"title": "Converted to Tezos", "subtitle": "Using ALGO Wallet", "header": "Converted 0.465322 XTZ ($2.91)", "health": "positive", "payment_method_name": "ALGO Wallet"}, "hide_native_amount": false}
  timestamp=202X-XX-XX 00:54:55 +0000
  asset=XTZ
  exchange=Coinbase
  holder=<<name>>
  transaction_type=Buy
  spot_price=6.253733973463537077550599370
  crypto_in=0.465322
  fiat_fee=0
  fiat_in_no_fee=2.91
  fiat_in_with_fee=2.91
  notes=None
```

On 0.3.25, I do see the OUT entry on the ALGO tab, and the IN entry on the XTZ tab.

I think the only thing I notice about this now is that in the raw transactions from coinbase's CSV, they consider the purchase of XTZ with a cost basis of 2.97, which is the sell price of the ALGO when converting.

**Comment by eprbell** [comment]
Thanks for this! So, the 2 trade ids matched, correct? Based on my reading of the raw data, I think you're right: it looks like they are showing the proceeds of the Algo sale as $2.97 and the cost basis of XTZ buy as $2.91. This means the fee is fiat-only (not crypto) and it's implicit in the native_amount difference between the two. The InTransaction and OutTransaction are the final result of the plugin swap handling code and they look OK to me. I think we can close the issue.

**Comment by jameskupke** [comment]
Yes, I matched by ID's and replaced all the occurrences with A's, then the next ID with all occurrences of B's. etc.

Are we sure that the issue can be closed? In DaLI, the OUT is 2.97, and the IN is 2.91 for the conversion. Wouldn't that incorrectly lower the Cost Basis by 6 cents?

**Comment by eprbell** [comment]
I'm not sure I understand what you mean by "lower the cost basis by 6 cents": could you clarify? There are two transactions of two different assets:
- ALGO Out/Sell: proceeds=$2.97
- XTZ In/Buy: cost basis=$2.91

If you look at the conversion as a whole, this captures the fact that you paid $0.06 in fees to Coinbase (so it's correct that the XTZ cost basis would be less than the ALGO proceeds. 

Does this make sense? Let me know if you interpret it differently or if I'm missing something.

**Comment by jameskupke** [comment]
Oh, ok. That makes sense. I didn't realize that the $0.06 was represented as a fee. I was expecting to see something with $2.97 to be listed in the XTZ IN table, is that not how it works?

Here's the output from the .ods file:

OUT |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Timestamp | Asset | Exchange | Holder | Transaction Type |   | Spot Price | Crypto Out No Fee | Crypto Fee | Crypto Out With Fee | USD Out No Fee | USD Fee | Unique ID | Notes
2021-XX-XX 00:54:56 +0000 | ALGO | Coinbase | ((name)) | Sell |   | $1.92 | 1.54924600 | 0.00000000 | 1.54924600 | $2.97 | $0.00 | AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA |  
TABLE END |   |   |   |   |   |   |   |   |   |   |   |   |  



IN |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Timestamp | Asset | Exchange | Holder | Transaction Type |   | Spot Price | Crypto In | Crypto Fee | USD In No Fee | USD In With Fee | USD Fee | Unique ID | Notes
2021XX-XX 11:19:03 +0000 | XTZ | Coinbase | (name) | Buy |   | $5.49 | 1.78610000 |   | $9.81 | $9.81 | $0.00 | BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBBBB | 
2021XX-XX 00:51:20 +0000 | XTZ | Coinbase | (name) | Buy |   | $6.24 | 0.23562900 |   | $1.47 | $1.47 | $0.00 | CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCCCC | 
2021XX-XX 00:53:40 +0000 | XTZ | Coinbase | (name) | Buy |   | $6.24 | 0.30754600 |   | $1.92 | $1.92 | $0.00 | DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD | 
2021XX-XX 00:54:55 +0000 | XTZ | Coinbase | (name) | Buy |   | $6.25 | 0.46532200 |   | $2.91 | $2.91 | $0.00 | EEEEEEEE-EEEE-EEEE-EEEE-EEEEEEEEEEEE | 


Shouldn't the IN file have USD In No Fee $2.91 and USD In With Fee as $2.97? It shows $2.91 for both values.

**Comment by eprbell** [comment]
Ok, I see your point and I think you're right: the in transaction should have USD In No Fee $2.91 and USD Fee as $0.06 so that its cost basis gets raised and the user gets a small deduction (or in alternative the fee could appear in the out transaction so that its proceeds get lowered, which would be equivalent in terms of deductions). The existing implementation misses a small deduction in Coinbase swaps (note that this doesn't affect Coinbase Pro swaps, which don't have this problem). I have to think a bit about the best way to implement this.

**Comment by eprbell** [comment]
@jameskupke I uploaded a new version of DaLI (0.3.27) with a fix for the missing fiat_fee issue. Unfortunately I can't test it because I don't have Coinbase swaps with a fee. Could you try it and let me know if the issue is resolved? Thanks!

**Comment by eprbell** [comment]
Actually try with 0.3.28 (or whatever is the very latest), thanks.

**Comment by jameskupke** [comment]
Reran with 0.3.28 and everything appears to be correct now. Closing this issue.

**Comment by eprbell** [comment]
Great, thanks for helping through all the iterations of this issue!

**Comment by eprbell** [comment]
@jameskupke, I just rewrote the coin conversion logic in the Coinbase plugin. Since you have an interesting transaction history, could I ask you to try the latest version of DaLI and make sure the numbers are unchanged? That would be a good test, beyond what I already have. Thanks!

**Comment by eprbell** [comment]
If needed, you can use the tests/ods_diff.py utility to generate a diff between two ODS files: this should help make sure the output hasn't changed in the new version.

**Comment by jameskupke** [comment]
Ok, here's the diff between 0.4.2 and 0.4.3:
[dali_0.4.2_0.4.3_diff.txt](https://github.com/eprbell/dali-rp2/files/8417347/dali_0.4.2_0.4.3_diff.txt)

I only removed my name and changed the transaction IDs, but they were all the same.

Looks like the only difference is on the sell side of conversions you have now linked the conversion transactions like on the buy side.

**Comment by jameskupke** [comment]
This was run with the -S flag as well.

**Comment by eprbell** [comment]
Thanks, so much! I appreciate your help. Yes, one of the changes is that now the notes are symmetric for buy and sell side.
