### ISSUE TITLE
Negative Transaction Fees and transaction_resolver errors

### ISSUE THREAD

**Issue by topherbuckley** [eprbell/dali-rp2#154]
As per [Issue 102](https://github.com/eprbell/dali-rp2/issues/102) there are some negative fees generated by bitbank. These appear to be causing a fatal error in the transaction resolver.  

Here is the traceback for the error:
```
Traceback (most recent call last):
  File "/media/christopher/HDD/git/dali-rp2/src/dali/dali_main.py", line 168, in _dali_main_internal
    resolved_transactions: List[AbstractTransaction] = resolve_transactions(transactions, dali_configuration, args.read_spot_price_from_web)
  File "/media/christopher/HDD/git/dali-rp2/src/dali/transaction_resolver.py", line 289, in resolve_transactions
    raise RP2RuntimeError(
rp2.rp2_error.RP2RuntimeError: Internal error: attempting to resolve two transactions that aren't Intra/Intra, In/Out or Out/In:
InTransaction:
  plugin=Bitbank.cc_REST
  unique_id=XXX
  raw_data={"timestamp": 1637583318405, "datetime": "2021-11-22T12:15:18.405Z", "symbol": "ETH/JPY", "id": "XXX", "order": "YYY", "type": "limit", "side": "sell", "takerOrMaker": "maker", "price": 477096.0, "amount": 0.1159, "cost": 55295.4264, "fee": {"currency": "JPY", "cost": 0.0}, "info": {"trade_id": "XXX", "order_id": "YYY", "pair": "eth_jpy", "side": "sell", "type": "limit", "amount": "0.1159", "price": "477096", "maker_taker": "maker", "fee_amount_base": "0.00000000", "fee_amount_quote": "-11.0591", "executed_at": "1637583318405"}, "fees": [{"currency": "JPY", "cost": 0.0}]}
  timestamp=2021-11-22 12:15:18+0000
  asset=JPY
  exchange=Bitbank.cc
  holder=christopher
  transaction_type=Buy
  spot_price=__unknown
  crypto_in=55295.4264
  fiat_fee=None
  fiat_in_no_fee=None
  fiat_in_with_fee=None
  notes=Buy side of conversion from 0.1159 ETH -> 55295.4264 JPY(ETH out-transaction unique id: XXX
InTransaction:
  plugin=Bitbank.cc_REST
  unique_id=XXX
  raw_data={"timestamp": 1637583318405, "datetime": "2021-11-22T12:15:18.405Z", "symbol": "ETH/JPY", "id": "XXX", "order": "YYY", "type": "limit", "side": "sell", "takerOrMaker": "maker", "price": 477096.0, "amount": 0.1159, "cost": 55295.4264, "fee": {"currency": "JPY", "cost": -11.0591}, "info": {"trade_id": "XXX", "order_id": "YYY", "pair": "eth_jpy", "side": "sell", "type": "limit", "amount": "0.1159", "price": "477096", "maker_taker": "maker", "fee_amount_base": "0.00000000", "fee_amount_quote": "-11.0591", "executed_at": "1637583318405"}, "fees": [{"currency": "JPY", "cost": -11.0591}]}
  timestamp=2021-11-22 12:15:18+0000
  asset=JPY
  exchange=Bitbank.cc
  holder=christopher
  transaction_type=Income
  spot_price=__unknown
  crypto_in=11.0591
  fiat_fee=None
  fiat_in_no_fee=None
  fiat_in_with_fee=None
  notes=Fee income for transaction #XXX
```
I may have been overly cautious, but I obfuscated the order ID and transactions to YYY and XXX respectively. 

It seems the transaction_resolver is trying to merge multiple transactions with the same unique ID. It appears the income fee has the same ID as the order in which the fee was generated. Is this the intended behavior? 

From what I've read so far it seems the fee should have a different unique_id when imported. since I don't think the rest of this is setup to handle negative fees on top of income from the transaction itself (i.e. there is no way to merge them into a single transaction as the transaction_resolver is attempting to do so). Can someone point me to where the unique_id is assigned to a transaction that does not explicitly specify it? Once I know where that is coming from I might be able to resolve this myself and add a PR unless others think they can do it more speedily.

**Comment by topherbuckley** [comment]
Looking into this more, it looks like the `trades` from [here](https://github.com/eprbell/dali-rp2/blob/b9a36fcc3cc5aad87b4a95a55d09d15f7de037e8/src/dali/abstract_ccxt_input_plugin.py#L314) gets the id from bitbank, and this id is used as the unique id [here](https://github.com/eprbell/dali-rp2/blob/b9a36fcc3cc5aad87b4a95a55d09d15f7de037e8/src/dali/plugin/input/rest/bitbank.py#L124). 

So bitbank is assigning the same id to both the fee and transaction (which I guess is what I'd expect). That being said, if we tried to combine them into a single transaction in dali, we'd end up missing the fee as a taxable income. 

So we can either:

1. Make necessary changes to include fee as a possible source of income (that'd be more work than I can commit atm)
2. Generate a new id for the fee and ensure it will be different from all other ids. Anyone here have any good ideas on how to ensure this? I'm guessing simply adding a number would not cut it. Also this kind of removes auditability by removing the connection between the fee and the actual trade id, so I'm not a huge fan of that. 
3. Add some logic in the transaction_resolver to handle this case (i.e. identical trade ID, but do not try to combine the transactions and keep them separate). I think I like this path the best as it preserves auditability and wouldn't take much to implement from what I can tell.

**Comment by topherbuckley** [comment]
I'm not sure if it is ok to leave the two transactions unresolved or if that messes up something else, but if we must resolve them, another possible solution would be to add a resolver for this case and add the fee to the crypto_in.

**Comment by macanudo527** [comment]
You are selling ETH, right? I've only bought it, so this wouldn't have come up with my real-world testing.

I would just add "M", to denote it is income from being the maker, to the end of the transaction id, or something similar. During an audit, you can still match up the transactions. 

The transaction can't be resolved anyway since it is income and not one side of conversion. The transaction resolver links two transactions together in the event of a conversion. However, this is a buy and doesn't need to be resolved.

**Comment by eprbell** [comment]
I would append "/fee" to the fee transaction and nothing to the regular transaction.

**Comment by macanudo527** [comment]
> I would append "/fee" to the fee transaction and nothing to the regular transaction.
This actually makes the best sense. That would be my solution, too.

**Comment by Larision** [comment]
```
Traceback (most recent call last):
  File "/home/kali/renta/dali-rp2/src/dali/dali_main.py", line 168, in _dali_main_internal
    resolved_transactions: List[AbstractTransaction] = resolve_transactions(transactions, dali_configuration, args.read_spot_price_from_web)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/renta/dali-rp2/src/dali/transaction_resolver.py", line 289, in resolve_transactions
    raise RP2RuntimeError(
rp2.rp2_error.RP2RuntimeError: Internal error: attempting to resolve two transactions that aren't Intra/Intra, In/Out or Out/In:
InTransaction:
  plugin=Binance.com_REST
  unique_id=XXX760BNB
  raw_data={"id": "XXX760BNB", "timestamp": 1648564129000, "datetime": "2022-03-29T14:28:49.000Z", "symbol": "BNB/USDT", "order": "XXX760", "type": null, "takerOrMaker": null, "side": "buy", "amount": 8.313e-05, "price": 439.07133405509444, "cost": 0.0365, "fee": {"currency": "BNB", "cost": 1.66e-06}, "info": {"fromAsset": "USDT", "amount": "0.0365", "transferedAmount": "0.00008313", "serviceChargeAmount": "0.00000166", "operateTime": "1648564129000", "transId": "XXX760", "isDustTrade": true}}
  timestamp=2022-03-29 14:28:49+0000
  asset=BNB
  exchange=Binance.com
  holder=fran
  transaction_type=Buy
  spot_price=__unknown
  crypto_in=0.00008313
  fiat_fee=None
  fiat_in_no_fee=None
  fiat_in_with_fee=None
  notes=Buy side of conversion from 0.0365 USDT -> 8.313e-05 BNB(USDT out-transaction unique id: XXX760BNB
InTransaction:
  plugin=Binance.com_REST
  unique_id=XXX760BNB
  raw_data={"id": "XXX760BNB", "timestamp": 1648564129000, "datetime": "2022-03-29T14:28:49.000Z", "symbol": "BNB/BTC", "order": "XXX760", "type": null, "takerOrMaker": null, "side": "buy", "amount": 0.09148394, "price": 0.00918500012133277, "cost": 0.00084028, "fee": {"currency": "BNB", "cost": 0.00182967}, "info": {"fromAsset": "BTC", "amount": "0.00084028", "transferedAmount": "0.09148394", "serviceChargeAmount": "0.00182967", "operateTime": "1648564129000", "transId": "XXX760", "isDustTrade": true}}
  timestamp=2022-03-29 14:28:49+0000
  asset=BNB
  exchange=Binance.com
  holder=fran
  transaction_type=Buy
  spot_price=__unknown
  crypto_in=0.09148394
  fiat_fee=None
  fiat_in_no_fee=None
  fiat_in_with_fee=None
  notes=Buy side of conversion from 0.00084028 BTC -> 0.09148394 BNB(BTC out-transaction unique id: XXX760BNB
```
I have this one in binance, same unique_id, maybe change small assets to BNB? but dont understand why same id.

Any idea?

**Comment by topherbuckley** [comment]
> ```
> Traceback (most recent call last):
>   File "/home/kali/renta/dali-rp2/src/dali/dali_main.py", line 168, in _dali_main_internal
>     resolved_transactions: List[AbstractTransaction] = resolve_transactions(transactions, dali_configuration, args.read_spot_price_from_web)
>                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/kali/renta/dali-rp2/src/dali/transaction_resolver.py", line 289, in resolve_transactions
>     raise RP2RuntimeError(
> rp2.rp2_error.RP2RuntimeError: Internal error: attempting to resolve two transactions that aren't Intra/Intra, In/Out or Out/In:
> InTransaction:
>   plugin=Binance.com_REST
>   unique_id=XXX760BNB
>   raw_data={"id": "XXX760BNB", "timestamp": 1648564129000, "datetime": "2022-03-29T14:28:49.000Z", "symbol": "BNB/USDT", "order": "XXX760", "type": null, "takerOrMaker": null, "side": "buy", "amount": 8.313e-05, "price": 439.07133405509444, "cost": 0.0365, "fee": {"currency": "BNB", "cost": 1.66e-06}, "info": {"fromAsset": "USDT", "amount": "0.0365", "transferedAmount": "0.00008313", "serviceChargeAmount": "0.00000166", "operateTime": "1648564129000", "transId": "XXX760", "isDustTrade": true}}
>   timestamp=2022-03-29 14:28:49+0000
>   asset=BNB
>   exchange=Binance.com
>   holder=fran
>   transaction_type=Buy
>   spot_price=__unknown
>   crypto_in=0.00008313
>   fiat_fee=None
>   fiat_in_no_fee=None
>   fiat_in_with_fee=None
>   notes=Buy side of conversion from 0.0365 USDT -> 8.313e-05 BNB(USDT out-transaction unique id: XXX760BNB
> InTransaction:
>   plugin=Binance.com_REST
>   unique_id=XXX760BNB
>   raw_data={"id": "XXX760BNB", "timestamp": 1648564129000, "datetime": "2022-03-29T14:28:49.000Z", "symbol": "BNB/BTC", "order": "XXX760", "type": null, "takerOrMaker": null, "side": "buy", "amount": 0.09148394, "price": 0.00918500012133277, "cost": 0.00084028, "fee": {"currency": "BNB", "cost": 0.00182967}, "info": {"fromAsset": "BTC", "amount": "0.00084028", "transferedAmount": "0.09148394", "serviceChargeAmount": "0.00182967", "operateTime": "1648564129000", "transId": "XXX760", "isDustTrade": true}}
>   timestamp=2022-03-29 14:28:49+0000
>   asset=BNB
>   exchange=Binance.com
>   holder=fran
>   transaction_type=Buy
>   spot_price=__unknown
>   crypto_in=0.09148394
>   fiat_fee=None
>   fiat_in_no_fee=None
>   fiat_in_with_fee=None
>   notes=Buy side of conversion from 0.00084028 BTC -> 0.09148394 BNB(BTC out-transaction unique id: XXX760BNB
> ```
> 
> I have this one in binance, same unique_id, maybe change small assets to BNB? but dont understand why same id.
> 
> Any idea?

Not sure, but one thing that stands out is that one of these is BNB bought using USDT and the other BTC. Also, neither is a negative fee, so I'd say open a new issue as it doesn't look related to this one.

**Comment by eprbell** [comment]
It is similar in the sense that it's also two different in-transactions with the same unique id, but it may be a different part of the code, since this is the Binance plugin instead of the Bitbank one. I agree that it would be best to open a new issue.

**Comment by macanudo527** [comment]
I second that, I'd like to discuss this further, but in a different issue. Could you also let us know what kind of transaction this was on Binance. It seems like this was a dust trade. Could you confirm that? (in a separate issue).

**Comment by eprbell** [comment]
@topherbuckley, is this issue resolved?
