### ISSUE TITLE
Unrecognized dividends in binance

### ISSUE THREAD

**Issue by Larision** [eprbell/dali-rp2#175]
ERROR: WARNING: Unrecognized Dividend: launchpad. Please open an issue at https://github.com/eprbell/dali-rp2/issues
ERROR: WARNING: Unrecognized Dividend: NFT airfrop Nov-BTTC. Please open an issue at https://github.com/eprbell/dali-rp2/issues
ERROR: WARNING: Unrecognized Dividend: Savings Trail Fund. Please open an issue at https://github.com/eprbell/dali-rp2/issues
ERROR: WARNING: Unrecognized Dividend: Cash Voucher. Please open an issue at https://github.com/eprbell/dali-rp2/issues

ERROR: WARNING: Unrecognized Dividend: DeFi Staking. Please open an issue at https://github.com/eprbell/dali-rp2/issues
ERROR: WARNING: Unrecognized Dividend: Defi Staking. Please open an issue at https://github.com/eprbell/dali-rp2/issues
check those 2 warnings, not same error, DeFi and Defi not same dividend.... :S

**Comment by macanudo527** [comment]
Wow, that's a lot. Can you give a brief explanation for each of these?

There are basically 10 different classifications for income:
AIRDROP, BUY, DONATE, GIFT, HARDFORK, INCOME, INTEREST, MINING, STAKING or WAGES

My guess is launchpad is STAKING?
NFT airfrop Nov-BTTC is an AIRDROP? Is it actually spelled airfrop?
DeFi Staking is STAKING obviously.
Savings Trail Fund is INTEREST?
Cash Voucher is GIFT?

This is easy to fix if you let me know the classifications.

**Comment by Larision** [comment]
> My guess is launchpad is STAKING? NFT airfrop Nov-BTTC is an AIRDROP? Is it actually spelled airfrop? DeFi Staking is STAKING obviously. Savings Trail Fund is INTEREST? Cash Voucher is GIFT?

launchpad is and ICO so i think its a BUY?
NFT airfrop Nov-BTTC i think its an special event past november, sure AIRDROP. dunno why called airfrop.... :S
DeFi staking and Defi stacking are STACKING
Saving trail funds is INTEREST
and cash vouchers are GIFT, yes

**Comment by macanudo527** [comment]
I'm pretty sure you can fix this yourself actually. The code is [here](https://github.com/eprbell/dali-rp2/blob/4969740753cc453810e7d384d8534b4d177f752a/src/dali/plugin/input/rest/binance_com.py#LL134C1-L148C92). You just need to add a unique variable with the string from the dividend like so:
```
_LAUNCHPAD: str = "launchpad"
```
And then add it to one of the lists below that.

I'm not sure what a cash voucher would be though. I don't think it's a GIFT. It might be INCOME. 

@eprbell, do you think a cash voucher from a crypto exchange would be INCOME. These are given out by Binance.com to incentivize people to invest in a new asset or try some new service typically. I see gift as being between two private entities. Of course, I understand that this is DYOR and you are not a tax professional, but what are your thoughts?

**Comment by eprbell** [comment]
I agree: INCOME is probably the closest transaction type we have to describe something like that.
