### ISSUE TITLE
Missing fiat to crypto transactions in binance

### ISSUE THREAD

**Issue by Larision** [eprbell/dali-rp2#179]
Im missing all EUR -> crypto not-direct (i mean EUR deposit and later EUR to crypto) transactions.

EUR -> crypto direct buys showing...

please tell me if need any log or something.

Thanks

**Comment by macanudo527** [comment]
Since I don't deposit or withdraw fiat from Binance.com that part of the plugin is completely untested.

So you are saying the fiat deposits are missing? AND the buy? That seems odd. I can see where the fiat deposit is missing but the buy should be there.

What do you mean by direct buys?

**Comment by Larision** [comment]
Im checking deep in dali logs and binance´s historical data.

- dali not showing any fiat deposit in logs - binance data has 20 of them.

- dali showing 2 buys with fiat ( EUR -> USDT) - binance shows 16

i maybe found a clue about it. The 2 transactions dali shows had a BNB fee. All the others had € fee or no fee.

Can be around fee asset this issue?

**Comment by Larision** [comment]
i discovered a pair of interesting things with those transactions.

- wrong code in binance_com fiat_deposits: not only fiat_payments using beginTime but fiat_deposits withrawal too.
- fiat_deposits and withrawals not using status : completed but successful.
- missing transactions EUR-USDT are convert trades and not processed by dali.
