### ISSUE TITLE
Implement FTX.US REST API Data Loader Plugin

### ISSUE THREAD

**Issue by eprbell** [eprbell/dali-rp2#2]
Writing a DaLI data loader plugin has high impact on the functionality and usefulness of both [DaLI](https://github.com/eprbell/dali-rp2) and [RP2](https://github.com/eprbell/rp2). Data loader plugins are well-defined, encapsulated modules that translate native exchange REST API-based data into DaLI's standard format. As such they are good first issues for newcomers to the the project.

Before starting, please read the [contributing guidelines](https://github.com/eprbell/dali-rp2/blob/main/CONTRIBUTING.md#contributing-to-the-repository).

Plugin development is described in the [developer documentation](https://github.com/eprbell/dali-rp2/blob/main/README.dev.md), in particular read the [Dali Internals](https://github.com/eprbell/dali-rp2/blob/main/README.dev.md#dali-internals) and [Plugin Development](https://github.com/eprbell/dali-rp2/blob/main/README.dev.md#plugin-development) sections, which contain all the information needed to build a new data loader plugin.

FTX.US REST API is documented here: https://docs.ftx.us/#rest-api

The [Coinbase plugin](https://github.com/eprbell/dali-rp2/blob/main/src/dali/plugin/input/rest/coinbase.py) can be used as an example.

Before submitting a PR for the new plugin, make sure to go through the [DaLI Plugin Laundry List](https://github.com/eprbell/dali-rp2/blob/main/README.dev.md#plugin-laundry-list).

**Comment by macanudo527** [comment]
This should be probably closed for now at least.
