### ISSUE TITLE
USD->EUR not found on any pair converter plugin

### ISSUE THREAD

**Issue by lockevod** [eprbell/dali-rp2#209]
Hello! Great tool! I'm using binance plugin and it's working fine but i've always this errror, I think it's clear but i don't know howto solve (I live in spain and we use EUR)

Regards

**Comment by macanudo527** [comment]
Are you using the CCXT pricing plugin?

**Comment by lockevod** [comment]
Yes, i've check with binance lock, general conf and without any converter (default converter). I use -s option also.

My conf.

# Data loaders
[dali.plugin.input.rest.binance_com sergi]
account_holder = sergi
api_key = XXXXXXXXX
api_secret = XXXXXXXXXXX
native_fiat=EUR

[dali.plugin.pair_converter.ccxt]
historical_price_type = nearest
default_exchange = Binance.com
google_api_key = XXXXXXXXX

**Comment by lockevod** [comment]
The complet error is

ERROR: Fatal exception occurred:
Traceback (most recent call last):
  File "/Users/sergi/crypto/dali-rp2/src/dali/dali_main.py", line 193, in _dali_main_internal
    resolved_transactions: List[AbstractTransaction] = resolve_transactions(transactions, dali_configuration, args.read_spot_price_from_web)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sergi/crypto/dali-rp2/src/dali/transaction_resolver.py", line 259, in resolve_transactions
    transaction = _convert_fiat_fields_to_native_fiat(transaction, global_configuration)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sergi/crypto/dali-rp2/src/dali/transaction_resolver.py", line 187, in _convert_fiat_fields_to_native_fiat
    raise RP2RuntimeError(f"Conversion rate for {transaction.timestamp_value}:{from_fiat}->{to_fiat} not found on any pair converter plugin")
rp2.rp2_error.RP2RuntimeError: Conversion rate for 2023-08-29 23:05:58+00:00:USD->EUR not found on any pair converter plugin
INFO: Log file: ./log/rp2_2023_10_03_12_31_35_596868.log
INFO: Generated output directory: output
INFO: Done

**Comment by lockevod** [comment]
If i change 
native_fiat=EUR => native_fiat=USD 

I have the same error

**Comment by macanudo527** [comment]
@lockevod this should have been resolved with #211 . Can you give it a try and let us know if you are getting correct pricing?

**Comment by macanudo527** [comment]
I'm closing this as resolved. If the problem crops again, let use know.
