### ISSUE TITLE
Difficulty creating fee-only out-transactions

### ISSUE THREAD

**Issue by cryptocactus77** [eprbell/dali-rp2#21]
Hi, 

I've been testing DaLI and have had trouble with including fee-only out-transactions in my **out_csv_file**

I'm getting this error: **rp2.rp2_error.RP2ValueError: Invalid keyword: FEE**

I'm using the latest **rp2** (0.9.26) and **dali-rp2** (0.4.1) python packages.

I've attached my **in_csv_file** and **out_csv_file**. 

[in_binance.csv](https://github.com/eprbell/dali-rp2/files/8403419/in_binance.csv)
[out_binance.csv](https://github.com/eprbell/dali-rp2/files/8403420/out_binance.csv)

**Comment by eprbell** [comment]
Thanks for reporting! I was able to repro right away with the files you uploaded. Fix incoming...

**Comment by eprbell** [comment]
Ok, the new version is up: could you refresh your DaLI installation and try again?

**Comment by cryptocactus77** [comment]
I seem to be getting this new error: **ValueError: invalid literal for int() with base 10: '<thread_count>'**

I've attached the log: 
[rp2_2022_04_02_15_29_20_307981.log](https://github.com/eprbell/dali-rp2/files/8403469/rp2_2022_04_02_15_29_20_307981.log)

**Comment by eprbell** [comment]
Could you paste here the `[dali.plugin.input.csv.manual]` of your .ini file?

**Comment by cryptocactus77** [comment]
Okay, this makes more sense now! Thanks for clueing me in. I was in the middle of adding Coinbase and Coinbase Pro plugins when trying again. Here's the full content of the .ini file below. I'm going to get rid of the Coinbase plugins and try again. 

[dali.plugin.input.csv.manual]
in_csv_file = input/in_binance.csv
out_csv_file = input/out_binance.csv
intra_csv_file = input/test_manual_intra.csv

[dali.plugin.input.rest.coinbase <qualifiers>]
account_holder = <account_holder>
api_key = <api_key>
api_secret = <api_secret>
thread_count = <thread_count>

[dali.plugin.input.rest.coinbase_pro <qualifiers>]
account_holder = <account_holder>
api_key = <api_key>
api_secret = <api_secret>
api_passphrase = <api_passphrase>
thread_count = <thread_count>

**Comment by eprbell** [comment]
No problem! Keep in mind that the strings in `<...>` are supposed to be substituted with your specific values. I think the error you were seeing was due to leaving the placeholder strings in the file: `ValueError: invalid literal for int() with base 10: '<thread_count>'`

**Comment by cryptocactus77** [comment]
It worked when I got rid of the Coinbase plugins! 

I changed up my **out_csv_file** since the amount of crypto used as a fee should actually go into the Crypto Fee column and not the Crypto Out No Fee column. 

Here are the new csv files to successfully reproduce a fee-only transaction: 
[in_binance.csv](https://github.com/eprbell/dali-rp2/files/8403495/in_binance.csv)
[out_binance.csv](https://github.com/eprbell/dali-rp2/files/8403496/out_binance.csv)

Thank you @eprbell !

**Comment by eprbell** [comment]
Great!
