### ISSUE TITLE
Implement Authentication for Exchangerate.host

### ISSUE THREAD

**Issue by macanudo527** [eprbell/dali-rp2#211]
### What? Why?

Exchangerate.host, the site that provides fiat prices has recently implemented access keys in order to access their pricing services. Users will be required to provide access keys in order to convert fiat amounts. The free tier allows 1000 requests/month, which should be enough for most users.

Came up in #207 
Will probably fix #209 

### Steps to Reproduce
Try to pull any kind of report in dali_rp2 that requires a fiat conversion e.g. USD->EUR

### Expected Behavior
Conversion of Fiat should be handled by exchangerate.host

### Actual Behavior
Dali-RP2 exits with an error stating that the conversion can not be found on any plugin.

### Priority/Severity
high - Reporting of most trades in a currency other than USD is affected.

### References
[Exchangerate.host](https://exchangerate.host/)
[Exchangerate.host Plans](https://exchangerate.host/product)
[Exchangerate.host API documentation](https://exchangerate.host/documentation)

**Comment by macanudo527** [comment]
@eprbell Now that this requires an access key, I'm wondering if we should add vcrpy to record the HTTP requests and play them back. I know you are trying to keep this minimal, but vcrpy would only be necessary for testing.

**Comment by macanudo527** [comment]
The free plan only covers USD as the source (ie. we can only convert from USD to another currency). This should be okay since more often than not if the base asset is not in the user's native fiat, it is usually available in USD anyway, so the conversion is almost always USD to something else.

However, we might want to look into alternative sources for historical fx data.

**Comment by eprbell** [comment]
I wasn't familiar with vcrpy, so I took a quick look: sounds like a good idea to me. Mocking network access is very important in tests and if this helps us do that, let's go for it.

Looking for alternatives sounds like a good idea: I'll also take a look to see what's out there.
