### ISSUE TITLE
Website Error: Running test under Windows 10 (config filename issue)

### ISSUE THREAD

**Issue by steveday72** [eprbell/dali-rp2#226]
I'm a total newbie to RP2 and DaLI (and have very limited experience with Python), but found a problem while trying to set it up today..

On the DaLI website, under section "Running", it says the following:

> Finally compute taxes with RP2 using the generated input files (using both FIFO and LIFO accounting methods):
> 
> rp2_us -m fifo -o output/ -p rp2_ output/test_crypto_data.config output/test_crypto_data.ods
> rp2_us -m lifo -o output/ -p rp2_ output/test_crypto_data.config output/test_crypto_data.ods
> 

Executing this on Windows 10 returns an error, saying that it could not find a file named "**output/test_crypto_data.config**".

This is because, _(at least on Windows)_, the config file generated by DaLI was named "**output/test_crypto_data.ini**". (_The filetype was ".ini" not ".config"_).

Replacing ".config" with ".ini" allowed it to run on my installation, which was installed using "pip".

eg:
> rp2_us -m fifo -o output/ -p rp2_ output/test_crypto_data.ini output/test_crypto_data.ods
> rp2_us -m lifo -o output/ -p rp2_ output/test_crypto_data.ini output/test_crypto_data.ods

**Comment by eprbell** [comment]
Thanks for reporting! I think you may be using an outdated version of the documentation. Check the latest version on Github: https://github.com/eprbell/dali-rp2?tab=readme-ov-file#running

Here's a screenshot:
![Screenshot 2024-03-14 at 4 34 24 PM](https://github.com/eprbell/dali-rp2/assets/77937475/8c01f8e9-d57e-4c4c-bcf2-dadd56670eb6)

**Comment by steveday72** [comment]
Thanks for the quick reply.

The URL that has the old info is:  https://pypi.org/project/dali-rp2/#running

I ended up there by following the link on the DaLI-RP2 main GitHub page, which says:
> **Download**
> The latest version of DaLI can be downloaded at: https://pypi.org/project/dali-rp2/

I see now that the two are out of sync.

**Comment by eprbell** [comment]
Ah, got it. This means I need to make a new official release for Pypi: there have been several bug fixes and improvements so I need to do that. I'll try in the weekend. Thanks again for reporting!

**Comment by macanudo527** [comment]
I'm closing this as it looks like this issue is resolved. Please let us know if you need further help.
