### ISSUE TITLE
Large file download warning not visible before accepting

### ISSUE THREAD

**Issue by X1011** [eprbell/dali-rp2#240]
Ok, this will be my last issue report for now 😄 
When I ran DaLI and got to the point where it downloads the Unified CSV File zip from Kraken, it did not show the message about what the file is that it's asking about. It seems like the progress bar rendered too early and overwrote the message, or maybe an output buffer needs to be flushed? This is the log (note the messages printed way to the right, after the progress bar:
```
INFO: Country: us
INFO: Initialized input plugin 'dali.plugin.input.csv.manual'
INFO: Initialized pair converter plugin 'dali.plugin.pair_converter.ccxt'
INFO: Reading crypto data using plugin 'dali.plugin.input.csv.manual'
INFO: Building manifest to optimize price calculation with the pair converters.
INFO: Resolving transactions
  0% |                                                                                                | Elapsed Time: 0:00:00 ETA:  --:--:--Do you want to download the file now?[yn]y
```
Above here outputted before I confirmed with 'y', and the following printed after:
```
INFO:
In order to provide accurate pricing from Kraken, a large (3.9+ gb) zipfile needs to be downloaded.
INFO: Downloading the unified CSV from https://drive.usercontent.google.com/download?id=16YKyFkYlvawCHv3W7WuTFzM8RYgMRWMt&export=download&confirm=t&uuid=f741c07c-64cf-4ee5-acf4-7b7f50309478
Downloading: |                                                        #                                              |   3.9 GiB  33.6 MiB/s
Downloading: |                                                        #                                              |   3.9 GiB  33.6 MiB/sINFO: Attempting to retrieve USDTUSD pair from the unified Kraken CSV file.
```

**Comment by X1011** [comment]
I didn't try resizing the terminal. I'm on macOS Sonoma 14.4.1.

I'm actually having trouble reproducing it now: I ran it from a different directory without `.dali_cache`, but it just ran through and processed everything without downloading the CSV. 🤔

**Comment by macanudo527** [comment]
Closing this and consolidating it with #252
