### ISSUE TITLE
Add a country agnostic entry point

### ISSUE THREAD

**Issue by rapus95** [eprbell/dali-rp2#247]
extending https://github.com/eprbell/rp2/issues/124 into dali

**Comment by eprbell** [comment]
This is done: you can use `dali_generic` now.

**Comment by rapus95** [comment]
Tried to update, but it doesn't seem to fetch a new version as it still says I'm on 0.6.10, so I assume it might not be in there. How can I install the newer version? (windows 11 user who installed via pip) is there something like a beta-release branch I can select for the pip install? (Never used pip aside of copy-pasting commands)

**Comment by eprbell** [comment]
I haven't done a new Dali release yet. Until then you can access the new features using the top of tree version: https://github.com/eprbell/dali-rp2/blob/main/README.dev.md#setup
