### ISSUE TITLE
Any suggestions how to handle situations where balance goes temporarily to zero?

### ISSUE THREAD

**Issue by EeroHeikkinen** [eprbell/dali-rp2#257]
For example on Kraken and Bitfinex, it can happen that an asset's balance will temporarily go to a small amount below zero. The situation is fixed by automatically selling some asset within a few minutes.
However, rp2 will not accept historical data like and will error out if the sell amount goes above the buy amount.
Any suggestions for fixes or workarounds how historical data like this could be remedied? 

I was thinking of adding a dummy in transaction with amount of say 0.1 and selling it at the end at the same price, but this feels likely to mess up the calculations in some way.

**Comment by eprbell** [comment]
You can use the -n option in RP2, to allow negative balances.
