### ISSUE TITLE
Coinbase Plugin Process Account Bug

### ISSUE THREAD

**Issue by macanudo527** [eprbell/dali-rp2#26]
According to the documentation the json response for Coinbase should be:

> {
>   "pagination": {
>     "ending_before": null,
>     "starting_after": null,
>     "limit": 25,
>     "order": "desc",
>     "previous_uri": null,
>     "next_uri": null
>   },
>   "data": [
>     {
>       "id": "58542935-67b5-56e1-a3f9-42686e07fa40",
>       "name": "My Vault",
>       "primary": false,
>       "type": "vault",
>       "currency": "BTC",
>       "balance": {
>         "amount": "4.00000000",
>         "currency": "BTC"
>       },
>       "created_at": "2015-01-31T20:49:02Z",
>       "updated_at": "2015-01-31T20:49:02Z",
>       "resource": "account",
>       "resource_path": "/v2/accounts/58542935-67b5-56e1-a3f9-42686e07fa40",
>       "ready": true
>     },
>     {
>       "id": "2bbf394c-193b-5b2a-9155-3b4732659ede",
>       "name": "My Wallet",
>       "primary": true,
>       "type": "wallet",
>       "currency": "BTC",
>       "balance": {
>         "amount": "39.59000000",
>         "currency": "BTC"
>       },
>       "created_at": "2015-01-31T20:49:02Z",
>       "updated_at": "2015-01-31T20:49:02Z",
>       "resource": "account",
>       "resource_path": "/v2/accounts/2bbf394c-193b-5b2a-9155-3b4732659ede"
>     }
>   ]
> }

So, shouldn't:

> currency: str = account[_CURRENCY][_CODE]

just be:

> currency: str = account[_CURRENCY]

https://github.com/eprbell/dali-rp2/blob/4eecce97b4c329aae1a095000af625ead0dfbc80/src/dali/plugin/input/rest/coinbase.py#L401

**Comment by eprbell** [comment]
Unfortunately the Coinbase documentation is completely out-of-date and incorrect :-( The plugin has been written by reading the actual data that is returned by the endpoint and "reverse-engineering" it. In the specific case you mentioned (account processing) the data from the endpoint looks like this: 
```
{"id": "[snip]", "name": "BTC Wallet", "primary": true, "type": "wallet", "currency": {"code": "BTC", "name": "Bitcoin", "color": "[snip]", "sort_index": 100, "exponent": 8, "type": "crypto", "address_regex": "[snip]", "asset_id": "[snip]", "slug": "bitcoin"}, "balance": {"amount": "[snip]", "currency": "BTC"}, "created_at": "[snip]", "updated_at": "[snip]", "resource": "account", "resource_path": "[snip]", "allow_deposits": true, "allow_withdrawals": true}
```

**Comment by eprbell** [comment]
@macanudo527, OK to close this one?
