### ISSUE TITLE
dali-rp2 sliently exits, no errors, no output

### ISSUE THREAD

**Issue by Maitaikawika** [eprbell/dali-rp2#263]
Here's what happens when I try to run dali-rp2:

dherring@Davids-Mac-Pro dali_rp2 % dali_us -s -o output -p 2003_ config.ini
INFO: Country: us
INFO: Initialized input plugin 'dali.plugin.input.csv.manual'
INFO: No pair converter plugins found in configuration file: using default pair converters.
INFO: Reading crypto data using plugin 'dali.plugin.input.csv.manual'
INFO: Building manifest to optimize price calculation with the pair converters.
INFO: Resolving transactions
  0% |                                                                                                                   | Elapsed Time: 0:00:01 ETA:  11:14:05
dherring@Davids-Mac-Pro dali_rp2 %

It just instantly exists.  No log information written beyond what I just posted above.  output folder created if not exist, but no output written.

Here is my config.ini file:

# Global configuration

# Data loaders
[dali.plugin.input.csv.manual]
in_csv_file = in_csv_file.csv
out_csv_file = out_csv_file.csv
intra_csv_file = intra_csv_file.csv

The "in" and "out" files have around 9000 records in each, plus or minus. 

My exchanges are binance.us and kracken.  I'm using manual because as I read the documentation, there are not data loaders available for them yet. 

I have confirmed this same behavior when trying the test files you provide at github. Identical silent failure.

I have also confirmed this same behavior on both Ubuntu Linux (Linux Mint 21.3) with python 3.10.12 and MacOS Monterey 12.7.5 with python version 3.13.0.  dali_us version 0.6.11 installed with pip as per your instructions.

Please advise if further information required.

**Comment by macanudo527** [comment]
Yeah, sorry, this is an issue with the Historic Crypto pair converter plugin, that should be resolved with #262 . If you are technically minded, you can download that branch and try it out. Otherwise, we should get it pushed through soonish, maybe within a week?

You could try the [CCXT pair plugin](https://github.com/eprbell/dali-rp2/blob/main/docs/configuration_file.md#ccxt) which should work. It will use Kraken prices by default. However, it will need to download a 4gig CSV file to do that. It is more robust and offers more options though.

**Comment by Maitaikawika** [comment]
It would appear that the 4gb file this plugin needs is no longer available, either via the plugin or manual download.  At least that's the story I'm getting today.  My taxes are due tomorrow, so at this point I'll have to find some other way to process my data.  Not sure I can grab the branch associated with #262 but I might try it and see how far I get.

**Comment by macanudo527** [comment]
Sorry about that. Kraken most likely updated the file and forgot to update the link. They do that almost every time they update it. I emailed them. They usually fix it pretty quickly, but if you need something now I would recommend using the branch.

**Comment by Maitaikawika** [comment]
I did pull the branch and happy to report that dali works on your test data. 

And when I run it on a subset of my data, namely the data from 2023, it runs on that as well.

When I combine all my data, from 2022 and 2023, it runs for about 10 minutes then silently exits with no errors, no logs, and no output.

I’m currently attempting to see if I can identify perhaps a corrupted field or something in my 2022 data that might account for this behavior. Thus far, nothing found.

My 2022 data was processed with another software in early 2023 for taxes.  I am presently attempting to puzzle out how I might leverage that to get around having to feed 2022 data to dali and rp2.

Thank you for pointing me in the direction of the branch.  That at least got me a bit closer to where I need to be.

**Comment by macanudo527** [comment]
Can you get a 2022 file with pricing data? if you can, dali will not make a lookup. You can combine the 2022 with the 2023 that doesn't have pricing data.

Maybe the coinbase API only provides data from when it was up and running (around 2022?).

**Comment by macanudo527** [comment]
This should be permanently resolved with #264, so I'm closing it for now.
