### ISSUE TITLE
Question/Proposal on REST api configuration

### ISSUE THREAD

**Issue by macanudo527** [eprbell/dali-rp2#27]
Should we allow for a start time for REST APIs?

For example, Binance will often only give you the most recent transactions by default (e.g. last 30-90 days). You have to explicitly make a request with an earlier start time to get transactions before that. I could start from when the API came online, but it would be useful to limit the requested information to one particular month or tax year.

**Comment by eprbell** [comment]
RP2 needs the full history to compute taxes correctly, so we should start from the first transaction. In the worst case we can use [Jan 3 2009](https://en.wikipedia.org/wiki/History_of_bitcoin#Creation) :-D

**Comment by macanudo527** [comment]
I'll just use the first day the exchange opened its doors I guess. 

Any chance we can at least use a cache so we can make incremental pulls?

**Comment by eprbell** [comment]
Yes, you can use the cache to speed up development: 
* pass -c to DaLI and
* define cache_key in your plugin: e.g. https://github.com/eprbell/dali-rp2/blob/main/src/dali/plugin/input/rest/coinbase.py#L164

**Comment by macanudo527** [comment]
Okay, thanks, I'll try to work that in. My webdev brain still wants to shove everything into a database.

**Comment by eprbell** [comment]
:-D

Basically to use the cache there's almost nothing to do: the DaLI infrastructure does all the heavy-lifting. You just need to pass -c on the command line and define the one-liner `cache_key()` method (use the Coinbase plugin as boilerplate)
