### ISSUE TITLE
Question about the Coinbase 'trade' transaction type

### ISSUE THREAD

**Issue by macanudo527** [eprbell/dali-rp2#38]
I understand that Coinbase will list crypto to crypto trades as transaction type 'trade'. Is the buy side and sell side listed as two different transactions then? Is that why there is a matching process in the Coinbase plugin?

I'm just looking for some clarification because Binance does not list these as separate transactions a crypto to crypto trade comes across as one item.

My guess is that transaction types buy and sell are to and from fiat? and not a stable coin like USDT?

The load() function will need to return a buy and sell transaction in fiat for all crypto to crypto trades correct?

Put another way, when one crypto is traded for the other, we have to imagine a sale of the one crypto into fiat, then that fiat is used to buy the other crypto, and that becomes the basis cost for the purchased crypto. That's my basic understanding of taxes.

**Comment by eprbell** [comment]
Yes, Coinbase splits conversion in two and so the plugin has a postprocessing step to "connect" them: it adds notes, updates fees, etc. But this is specific to the Coinbase REST API: if Binance expresses conversions with one JSON structure you may not have to do that.

Also you're correct that in Coinbase buy/sell are from/to fiat and trade is used for crypto-to-crypto conversion. RP2 expresses conversions as one IN/BUY + one OUT/SELL (with the fee, if any, appearing in only one of the two): for more on this see https://github.com/eprbell/rp2/blob/main/docs/user_faq.md#how-to-handle-conversion-of-a-cryptocurrency-to-another. So the load function must return both transactions for every crypto conversion.

Let me know if you need more info.

**Comment by macanudo527** [comment]
I think I understand it now. It almost seems like each exchange does things a little differently. It's hard to find a consistent pattern.

**Comment by eprbell** [comment]
True, every exchange uses different JSON structures, however using CCXT should help: if it works as advertised CCXT should provide a common API for most operations (buy, sell, convert, etc) and so there should be limited or no need to use the native exchange API: hopefully never or perhaps only for some exotic exchange-specific things.
