### ISSUE TITLE
DaLI -s Flag not Returning Spot Prices

### ISSUE THREAD

**Issue by heiden12** [eprbell/dali-rp2#39]
When I run DaLI with the -s flag using the .csv.manual plugin and any of my input tables are missing spot prices DaLI is throwing the following error:

Exception: Internal error: spot_price is empty

**Comment by eprbell** [comment]
Can you provide additional details:
- full stack trace
- transaction that is causing the issue (anonymized)

Potentially this could be similar to what was discussed in #28.

**Comment by eprbell** [comment]
In particular check if this applies to the problem you're seeing: https://github.com/eprbell/dali-rp2/issues/28#issuecomment-1097299824

**Comment by eprbell** [comment]
I also updated the relevant FAQ with pointers to transaction resolution: https://github.com/eprbell/dali-rp2/blob/main/docs/user_faq.md#what-if-the-spot-price-is-missing-for-some-transactions

**Comment by heiden12** [comment]
The transactions I was hoping to get spot prices for are staking rewards so there is no crypto_fee or crypto_sent. Are staking rewards not supported yet?

**Comment by eprbell** [comment]
Staking is supported: perhaps there is some peculiarity with the Coinbase JSON. In order to understand what is happening I need a bit more information. Could you share the line from your debug logs that shows the JSON returned by Coinbase for this transaction?

Here's how to do it:
* prepend your dali command line with LOG_LEVEL=DEBUG
* after running dali in debug mode, cd to the log directory, open the latest log and look for the line of the culprit transaction (check in the Coinbase section of the log, you can look by timestamp or unique_id)
* be sure to anonymize the transaction before posting it here

If you can also post the generated transaction (from the ODS file) that would help too.

Thanks.

**Comment by heiden12** [comment]
Just to confirm the spot price look up should work on transactions found in the csv file specified by the in_csv_file?

**Comment by heiden12** [comment]
This would only be in the manual csv file since they are staking rewards deposited directly to a wallet.

**Comment by eprbell** [comment]
I need a couple of data points to understand what is happening:
* full stack trace
* culprit transaction (anonymized) from the manual csv file

**Comment by eprbell** [comment]
Can you write in `__UNKNOWN` as the spot price and try again?

**Comment by heiden12** [comment]
When using __UNKNOWN for the spot price I get the following:

Exception: Internal error parsing spot_price as number: __UNKNOWN
,October 27, 2021 - 09:39:41+00:00,ALGO,Algo-Wallet,Alex,Income,__UNKNOWN,0.0035,0,,,,
could not convert string to float: '__UNKNOWN'

The transaction from the csv is:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	
	
	<title></title>
	<meta name="generator" content="LibreOffice 6.1.5.2 (Linux)"/>
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"Liberation Sans"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	
</head>

<body>


unique_id | timestamp | asset | exchange | holder | transaction_type | spot_price | crypto_in | crypto_fee | fiat_in_no_fee | fiat_in_with_fee | fiat_fee | notes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | October 27, 2021 - 00:00:00+00:00 | ALGO | MyWallet | NAME| Income | __UNKNOWN | 0.0035 | 0 |   |   |   |  


</body>

</html>

**Comment by eprbell** [comment]
Thanks, that allowed me to repro the issue. Here are the problems:
* pass `__unknown`, not `__UNKNOWN` (this was my bad, sorry);
* the documentation of the manual plugin doesn't do a good job explaining the use of `__unknown`: I'll fix it shortly.

Thanks for reporting!

**Comment by eprbell** [comment]
Added more information on `__unknown` in the relevant FAQ: https://github.com/eprbell/dali-rp2/blob/main/docs/user_faq.md#what-if-the-spot-price-is-missing-for-some-transactions

Updated manual plugin documentation to discuss use of `__unknown` in spot_price: https://github.com/eprbell/dali-rp2/blob/main/docs/configuration_file.md#manual-section-csv

**Comment by eprbell** [comment]
@heiden12, is the issue resolved? Let me know if there are more problems.

**Comment by eprbell** [comment]
All issues have been addressed: closing. Please open a new issue if you have more questions.
