### ISSUE TITLE
Price calculation for one side of pair

### ISSUE THREAD

**Issue by stevendavis** [eprbell/dali-rp2#47]
Some transactions involve two tokens where the spot price of one or both tokens is not provided by the exchange. However, we have enough information to determine the spot prices of both tokens.  In a typical transaction, we know the following:
- price ratio of the swap pair -or- quantity of each token
- the price of one of the tokens is either known or can be looked up by the historic crypto service
- the price of the other token is not available in the historic crypto service

In this scenario, we can lookup the historic price of one of the tokens and calculate the historic price of the other token with a simple formula.  Are there any plans to add this capability to DaLi?

**Comment by eprbell** [comment]
You're raising a valid point. This scenario should be handled by [adding new pair converter plugins](https://github.com/eprbell/dali-rp2/blob/main/README.dev.md#pair-converter-plugin-development) that are more powerful than Historic Crypto (which doesn't support all the pairs we need: e.g. it has no fiat). For example, it would be great to add a CCXT-based pair converter: if you have time/interest in this, let me know. The CCXT-based plugin (and its ability to handle fiat, not just crypto) is required by @macanudo527's Binance plugin and by any future non-US exchange plugins. It can also become the default pair converter plugin, instead of HistoricCrypto. Right now pair converters and data loaders are the highest impact types of contribution to DaLI.

**Comment by eprbell** [comment]
I'll add a bit of context here, in case it's of interest. The new pair converter plugin architecture supports any number of plugins (just like the data loader plugin architecture). The user can specify which [pair converters to use in the .ini file](https://github.com/eprbell/dali-rp2/blob/main/docs/configuration_file.md#pair-converter-plugin-sections). Then when DaLI (and specifically the transaction resolver) needs to query a price, it will ask the first pair converter. If the price is unavailable it will move on to the second one, etc (so order matters in the .ini file). Currently we only have one plugin (Historic-Crypto) and we need to add more (CCXT and probably others).

**Comment by stevendavis** [comment]
@eprbell Thanks for following up. There may be some tokens that only exist on their native blockchain and don't trade on any CEX. Would the CCXT plugin have the capability to calculate the historic price of such a token when the other side of the pair is known?

**Comment by eprbell** [comment]
Even so, wouldn't this token's price history be kept on historical crypto services (like CoinMarketCap, etc.)? If you have a specific example of a token whose price history is not listed on any of these services we can look into the details and try to find a solution. In the context of pair converter plugins, CCXT would be used in the same way Historic-Crypto is being used in its [pair converter plugin](https://github.com/eprbell/dali-rp2/blob/main/src/dali/plugin/pair_converter/historic_crypto.py) (that is as a database of historic conversion rates).

An additional observation on conversions: the data loaders model them as two separate transactions (an in and an out transaction).

**Comment by stevendavis** [comment]
Good point.  There should be a historical crypto service, like CMC, that could provide a spot price for the token. This kind of lookup will not exactly match the spot price calculated by a formula, but maybe it's close enough and allows the user to move along and make progress on their taxes.

**Comment by eprbell** [comment]
Yes, but also we want to rely on documented records as much as possible: e.g. price history from CMC, etc. We should try and avoid creating synthetic numbers, because they're harder to defend in the context of an IRS audit.

**Comment by macanudo527** [comment]
I went ahead and opened a specific issue #48 for the pair converter plugin. I'm going to start work on it unless @stevendavis has started anything.

**Comment by stevendavis** [comment]
I have not started anything. Thank you @macanudo527 for your contributions.

**Comment by eprbell** [comment]
Closing this, since it's tracked in #48
