### ISSUE TITLE
Identical manual intra notes concatenated

### ISSUE THREAD

**Issue by stevendavis** [eprbell/dali-rp2#49]
A transfer transaction is recorded in two manual input intra files with matching unique ids and also identical notes. In the DaLi output file the notes appear as one long string with both notes, which now appear to be redundant.  Can this be detected programmatically to skip the concatenation when the notes are identical?

**Comment by eprbell** [comment]
Sounds OK to me, but it would be easier to look at code: want to open a PR?

**Comment by stevendavis** [comment]
Sure, I'll prepare a PR soon.

**Comment by stevendavis** [comment]
Closing with PR https://github.com/eprbell/dali-rp2/pull/51.
