### ISSUE TITLE
CSV manual prep of in and out files

### ISSUE THREAD

**Issue by jtourt** [eprbell/dali-rp2#57]
Is it correct that the manual CSV plugin expects to receive an "in" file that only contains purchases/acquisitions, and an "out" file that only contains sells/dispositions?   

Crypto exchanges generate CSV files with transaction histories that contain a mixture of all transactions, buys and sells.  Are there any exchanges that generate one CSV file that contains just purchases and another CSV file that contains just sales?  Since there are no exchanges that generate files in this manner, then either a custom script needs to be created to parse the exchange generated CSV files into the files that are ready for DaLI, or manual effort must be done to create the files by hand for DaLI.

Is this correct that a pre-processor is needed for the pre-processor (DaLI)?

**Comment by macanudo527** [comment]
Right now there are not a lot of plugins that can use the REST API of exchanges, which is the smoothest way to pull this kind of information. Currently, only Coinbase and CoinbasePro is available.

I'm working on a CCXT plugin that should open that up to all CCXT compatible exchanges, soonish, maybe in about 3-4 months? The CSV processor is just kind of a stop-gap measure until that is up and running. Is there a particular exchange you work with? I could try to start work on that as soon as I am done with the plugin for Binance.com.

**Comment by eprbell** [comment]
> Is it correct that the manual CSV plugin expects to receive an "in" file that only contains purchases/acquisitions, and an "out" file that only contains sells/dispositions?
> 
> Crypto exchanges generate CSV files with transaction histories that contain a mixture of all transactions, buys and sells. Are there any exchanges that generate one CSV file that contains just purchases and another CSV file that contains just sales? Since there are no exchanges that generate files in this manner, then either a custom script needs to be created to parse the exchange generated CSV files into the files that are ready for DaLI, or manual effort must be done to create the files by hand for DaLI.
> 
> Is this correct that a pre-processor is needed for the pre-processor (DaLI)?

It's correct that the manual plugin expects 3 files (in, out, intra). However DaLI has a plugin architecture for input plugins, so that people can contribute input plugins for any input format. So there is no need for a pre-processor to the pre-processor: to support a new input format, all that is needed is a new plugin. See the [Plugin Development](https://github.com/eprbell/dali-rp2/blob/main/README.dev.md#plugin-development) section of the developer documentation for more on this topic.

**Comment by eprbell** [comment]
Closing the issue. If you have more questions please open a new one.
