### ISSUE TITLE
how to model swaps?

### ISSUE THREAD

**Issue by houqp** [eprbell/dali-rp2#8]
Hi, I noticed in both the coinbase plugin and manual csv input, crypto concurrency swaps are not supported. Is this correct? If so, is there any workaround to model into the report? Do I need to split that into one acquire and one dispose transactions instead?

**Comment by eprbell** [comment]
Hello, swaps are supported in the Coinbase Pro plugin, but not (yet) in the Coinbase one. In the manual plugin (and in RP2 itself) swaps are modeled in the way explained in the [RP2 FAQ](https://github.com/eprbell/rp2/blob/main/docs/user_faq.md#how-to-handle-conversion-of-a-cryptocurrency-to-another). Hope this helps.

**Comment by houqp** [comment]
Thank you @eprbell , that's exactly what I was looking for!
