### ISSUE TITLE
Low Priority Feature Request: API Call Limiter

### ISSUE THREAD

**Issue by topcoderasdf** [eprbell/dali-rp2#83]
Currently we have to manually adjust thread_count for each exchange. However, each exchange specifies its own rate limit. 

So I think it would be nice to have some kind of api call limiter. Then we don't have to manually adjust thread_count.

In terms of api call limit, some exchanges limit based on individual endpoint, others limit based on UID (thus, all endpoints combined).

Binance for example,

> Each endpoint with IP limits has an independent 12000 per minute limit.
> Each endpoint with UID limits has an independent 180000 per minute limit.

https://binance-docs.github.io/apidocs/spot/en/#limits

Coinbase seems to limit only based on individual endpoint

> REST API
> For Public Endpoints, our rate limit is 3 requests per second, up to 6 requests per second in bursts. For Private Endpoints, our rate limit is 5 requests per second, up to 10 requests per second in bursts.

https://help.coinbase.com/en/pro/other-topics/api/faq-on-api

Kucoin seem to limit only based on UID

> REST API
> 
> The limit strategy of private endpoints will restrict account by userid. The limit strategy of public endpoints will restrict IP.

https://docs.kucoin.com/#request-rate-limit

**Comment by eprbell** [comment]
Do you mean an exponential backoff algorithm? E.g. try with n threads, if it fails, try again with n/2 threads, etc.?

**Comment by macanudo527** [comment]
A rate limiter is already built in to CCXT which is what, hopefully, most REST input plugins will be based on in the future. I don't think one will be necessary for Dali.

Multithreading will be useful in maximizing the API limits though. For example, allowing one thread to continue making calls to the API while another processes data that has already been returned. We still don't know enough about each exchange to build something universal though.

**Comment by eprbell** [comment]
Thanks, that's good to know. The CB plugins will migrate to the CCXT-based implementation: in fact the new abstract CCXT plugin class @macanudo527 is working on will be the standard foundation for all REST plugins.
