### ISSUE TITLE
Bundling PRs

### ISSUE THREAD

**Issue by macanudo527** [eprbell/dali-rp2#94]
I'm working through all my changes with real world data. I'm sure there will be small tweaks and fixes that will come up along the way. Should I bundle those all together even if they are across several plugins or do a PR for each?

**Comment by eprbell** [comment]
I tend to prefer one PR per issue (or at least related issues), but I don't want to put a lot of red tape in your way. Whatever works best for you is fine.

**Comment by macanudo527** [comment]
Thanks for clarifying.
