### ISSUE TITLE
Outdated version of virtualenv installing to local/bin and not bin

### ISSUE THREAD

**Issue by macanudo527** [eprbell/dali-rp2#97]
This isn't an issue with dali-rp2. There is a current issue with virtualenv where it installs to a `local/bin` folder instead of to `bin`. More details are [here](https://askubuntu.com/questions/1406304/virtualenv-installs-envs-into-local-bin-instead-of-bin).

It says the latest version doesn't have this issue, but I can't seem to install the latest from `apt-get`, so I had to use the workaround. This is just an FYI.

**Comment by macanudo527** [comment]
I did. This is also with a fresh install of Ubuntu. I had to pick up a new laptop since my old one finally gave up the ghost. That's why I've been a bit MIA for the last week or so. Anyway, I just thought I would mention it since it ate up 2~3 hours of my time hunting it down. Everything is working for me now, so I'm back to bug squashing.

**Comment by eprbell** [comment]
OK: hopefully the problem will disappear in time as meta packages are updated. In any case thanks for reporting!

**Comment by eprbell** [comment]
Trying to clean up issues: is it ok to close this one or should we leave it open?

**Comment by macanudo527** [comment]
I was leaving it open in case someone had the same issue, but it seems like others are installing without issue.
